name: OutputContext
on: push
jobs:
    info:
        name: Information
        runs-on: ubuntu-latest
        steps:
            - name: OutputGithubContext
              run : | 
                echo "${{ toJson(github) }}">githubifo.json
                ${{ toJson(github) }}>m.json
            - uses: actions/upload-artifact@v4
              with:
                name: drop
                path: ./githubifo.json ./m.json
