name: OutputContext
on: push
jobs:
    info:
        name: Information
        runs-on: ubuntu-latest
        steps:
            - name: OutputGithubContext
              run : env
                 # echo "$manoj"
                 # echo "${{ env.prod.manoj }}"
                 # echo "${{ toJson(github) }}">githubifo.json
               
            - uses: actions/upload-artifact@v4
              with:
                name: drop
                path: ./githubifo.json ./m.json
