name: OutputContext
on: push
jobs:
    info:
        name: Information
        runs-on: ubuntu-latest
        steps:
            - name: OutputGithubContext
              run : |
                echo $var
                 # echo "${{ toJson(github) }}">githubifo.json
              env:
               var: ${{ vars.manoj }}
            - uses: actions/upload-artifact@v4
              with:
                name: drop
                path: ./githubifo.json ./m.json
