name: OutputContext
on: 
  push:
  workflow_dispatch:
jobs:
    info:
        name: Information
        runs-on: ubuntu-latest
        steps:
            - name: OutputGithubContext
              run: |
                echo "repository variable : $REPOSITORY_VAR"
              env:
                REPOSITORY_VAR: ${{ vars.MANOJ }}
               
            - uses: actions/upload-artifact@v4
              with:
                name: drop
                path: ./githubifo.json ./m.json
