name: OutputContext
on: push
jobs:
    info:
        name: Information
        runs-on: ubuntu-latest
        steps:
            - name: OutputGithubContext
              run : |
                 env
                 env.production

                 # echo "$manoj"
                 echo "${{ env.production.manoj }}"
                 # echo "${{ toJson(github) }}">githubifo.json
               
            - uses: actions/upload-artifact@v4
              with:
                name: drop
                path: ./githubifo.json ./m.json
