name: OutputContext
on: 
  push:
  workflow_dispatch:

  
jobs:
    info:
        name: Information
        runs-on: ubuntu-latest
        environment: production
        steps:
            - name: OutputGithubContext
              run: |
                env
                echo $Ramu
                
                echo "${{ tojson(github) }}"
                echo "repository variable : $REPOSITORY_VAR , $Env"
              env:
                REPOSITORY_VAR: ${{ vars.MANOJ }}
                Env: ${{ vars.Ramu }}
               
            - uses: actions/upload-artifact@v4
              with:
                name: drop
                path: ./githubifo.json ./m.json
